### PR TITLE
Unit Testing Framework

### PR DESCRIPTION
**Pull request by BriannaRoskind**
Summary:
Added unit testing framework (and code coverage).

Files Added:

- mocks/aws-sdk-go/sagemaker/ApplicationAutoScalingAPI.go - Contains unit testing api mocks.
- pkg/testutil/test_suite_config.go - Defines structures related to the unit testing test suite.
- pkg/testutil/test_suite_runner.go - Contains main workflow functions for running unit tests.
- pkg/testutil/util.go - Contains helper functions used in test_suite_runner.go.
- scripts/install-mockery.sh - A script that installs the mockery CLI tool that is used to build Go mocks for our interfaces to use in unit testing.

Files Edited:

- Makefile - Defined unit testing, mock, and unit testing coverage related testing calls.

### CODE REVIEW

**Review by akartsky — APPROVED** [review]

**Comment by akartsky** [comment]
Can you add at least one unit test so that we know that setup is working

**Review by surajkota — COMMENTED** [review]
No changes to go.mod and attributions in this one?

**Comment by mbaijal** [comment]
> Can you add at least one unit test so that we know that setup is working

+1 to this - if it isn't too much work. Or could you let us know how this was tested ?

**Review by mbaijal — APPROVED** [review]

**Pull request merged**
