### PR TITLE
Add creationTime to Status for ScalableTarget and ScalingPolicy resources

### PR DESCRIPTION
**Pull request by mbaijal**
Issue #, if available:
aws-controllers-k8s/community#932

Description of changes:
Add creationTime to Status for ScalableTarget and ScalingPolicy resources based off of [code gen changes in this PR.](https://github.com/aws-controllers-k8s/code-generator/pull/183)

TODO: Add required check to the existing integration test.

Testing
Manually tested that the field is present in the Status of the `kubectl get` response. 
Kind tests pass locally

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
Nice addition, @mbaijal, thanks!

**Review by surajkota — COMMENTED** [review]
+1 need to make sure creation and last modified time are reported in the same time zone

if they are not, we can overwrite the creation time in custom code similar to modified time

**Comment by mbaijal** [comment]
> +1 need to make sure creation and last modified time are reported in the same time zone
> 
> if they are not, we can overwrite the creation time in custom code similar to modified time

Sure, but I am creating a separate PR for that since this is also a demo of the associated Code-gen change.

**Review by RedbackThomson — APPROVED** [review]
Great!
/lgtm

**Pull request merged**
